baseURL: "https://sxi.is-a.dev/"
title: "Sxinar"
DefaultContentLanguage: tr
theme: hugo-PaperMod

languages:
  tr:
    languageName: ":tr:"
    weight: 1
    params:
      languageAltTitle: Turkish
      homeInfoParams:
        Title: "Sxinar"
        Content: Burası benim teknoloji çiftliğim.

menu:
  main: 
    - identifier: Anasayfa
      name: Anasayfa
      url: /
      weight: 1
    - identifier: Blog
      name: Blog
      url: /post/
      weight: 2
    - identifier: İletişim
      name: İletişim
      url: /page/iletisim/
      weight: 6
    - identifier: Kategoriler
      name: Kategoriler
      url: /tags/
      weight: 3
    - identifier: Arşiv
      name: "Arşiv"
      url: /arsiv/
      weight: 5
    - identifier: Ara
      name: "Ara \U0001f50d"
      url: /ara/
      weight: 7

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    ShowShareButtons: true
    ShowReadingTime: true
    env: production
    ShowBreadCrumbs: true
    title: "Sxinar"
    description: "Açıklama"
    author: Sxinar
    DateFormat: "2 January, 2006"
    ShowPostNavLinks: true
    defaultTheme: auto
    rss: true
    ShowFullTextinRSS: true
    TocOpen: true
    ShowCodeCopyButtons: true
    comments: true
    fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    enableEmoji: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  
    socialIcons:
        - name: github
          url: "https://github.com/Sxinar"
        - name: email
          url: "mailto:me.unreal462@simplelogin.com"
        - name: rss
          url: "https://sxinar.github.io/index.xml"
        - name: gitlab
          url: "https://gitlab.com/Sxinar"
 
    assets:
        favicon: "https://btt.community/user_avatar/btt.community/sxinar/288/7779_2.png"

    editPost:
        URL: "https://github.com/sxinar/sxinar.github.io/tree/main/content"
        Text: "Suggest Changes"
        appendFilePath: true